print("CREATE DATABASE launchesdb;")

print("CREATE TABLE launches (")
print("launchID TEXT,")
print("launchDate TIMESTAMP,")
print("COSPAR TEXT,")
print("postPayload TEXT,")
print("prePayload TEXT,")
print("SATCAT TEXT,")
print("LV_type TEXT,")
print("LV_serial TEXT,")
print("launchSite TEXT,")
print("outcome TEXT")
print(");")

print("CREATE TABLE satellites (")
print("COSPAR TEXT,")
print("postPayload TEXT,")
print("prePayload TEXT,")
print("owner TEXT,")
print("SATCAT TEXT,")
print("orbitPrd TEXT, ")
print("orbitClass TEXT, ")
print("orbitPAI TEXT")
print(");")
